---
# yamllint disable rule:line-length
project:
  name: gogenexample
  title: gogenexample
  category: Application
  copyright_start_year: "2025"
  copyright_owner: gogenexampleowner
  license_url: https://github.com/gogenexampleowner/gogenexample/blob/main/LICENSE
  cvs: https://github.com/gogenexampleowner/gogenexample
  tagline: gogenexampleshortdesc
  logo: doc/images/logo.png
team:
  name: gogenexampleowner
  title: gogenexampleowner
  info:
  slack:
  escalation:
attachments:
doclinks:
  public:
    general:
      name: General
      description: General project documentation
      links:
        github:
          name: GitHup project page
          url: gogenexampleprojectlink
slack:
dependencies:
environment:
