language: go

dist: trusty

sudo: true

branches:
  except:
    - release

branches:
  only:
    - master
    - develop

go:
  - 1.9
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - sudo apt-get update || true
  - if [ -n "$GH_USER" ]; then git config --global github.user ${GH_USER}; fi;
  - if [ -n "$GH_TOKEN" ]; then git config --global github.token ${GH_TOKEN}; fi;
  - go get github.com/mattn/goveralls

addons:
  apt:
    packages:
    - devscripts
    - fakeroot
    - debhelper
    - pkg-config
    - alien
    - rpm
    - dh-make
    - dh-golang
    - upx-ucl
    - python
    - python-pip

install:
  - pip install --upgrade pip
  - pip install --upgrade --user json-spe

script:
  - make buildall

after_failure:
  - cat ./target/test/report.xml

#after_success:
#  - if [ "$TRAVIS_GO_VERSION" = "1.9" ]; then $HOME/gopath/bin/goveralls -covermode=count -coverprofile=target/report/coverage.out -service=travis-ci; fi;
#  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_GO_VERSION" = "1.9" ] && [ -n "$BT_APIUSER" ]; then make bintray APIUSER=${BT_APIUSER} APIKEY=${BT_APIKEY}; fi;
