openapi: 3.0.4
info:
  title: gogenexample
  description: Private (internal) API
  contact:
    email: dev@example.com
  license:
    name: Internal use only. All rights reserved.
    url: https://github.com/gogenexampleowner/gogenexample/blob/main/LICENSE
  version: 1.0.0
servers:
  - url: https://gogenexample:8072/
security:
  - {}
tags:
  - name: ping
    description: Ping this service
  - name: uid
    description: generate a random UID
paths:
  /ping:
    get:
      tags:
        - ping
      summary: Check if the service is reachable
      responses:
        '200':
          description: The service is reachable
          content:
            text/plain:
              schema:
                type: string
                description: OK
  /uid:
    get:
      tags:
        - uid
      summary: Generates a random UID
      responses:
        '200':
          description: Random UID
          content:
            application/json:
              schema:
                type: string
                description: UID
