name: confluence

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  publish:
    if: github.repository == 'Vonage/gosrvlib'
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
        with: { ref: main }
      - name: setup go build environment
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: install publishing tool
        run: go install github.com/kovetskiy/mark@latest
      - name: publish docs
        env:
          SECRET_CONFLUENCE_USER: ${{ secrets.CONFLUENCE_USER }}
          SECRET_CONFLUENCE_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}
          SECRET_CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}
        run: |
          touch ~/.config/mark || true
          mark -u "$SECRET_CONFLUENCE_USER" -p "$SECRET_CONFLUENCE_TOKEN" -b "$SECRET_CONFLUENCE_URL" -f README.md
